<!DOCTYPE html>
<html>
    <head>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/autogrow@1.0.6/autogrow.min.js"></script>

        <script type='text/javascript'>
            
            var getDomainsInfo = function (Domains, ExcludeActive) {
                
                $ ("#Loading").css ('visibility', 'visible');

                var PostData = {
                    "Ajax": true,
                    "action": "GetStatus", 
                    "ExcludeActive": ExcludeActive,
                    "Domains": Domains
                };

                $.post ("index.php", PostData, function (data) {
                    data = JSON.parse (data);
                    
                    $ ("#AjaxContent").html ("");

                    for (const errText in data ["Errors"]) {
                        $ ("#AjaxContent").append (
                            $ ("<p>").addClass ("text-warning").text (data ["Errors"][errText])
                        );
                    }
                    
                    if (Object.keys (data.Domains).length) {
                        
                        let table = $ ("<table>").addClass ("table table-bordered");
                    
                        for (let domain in data.Domains) {
                            let heading = $ ("<tr>").addClass ("thead-light"),
                                no_results = data.Domains [domain] === null || (Array.isArray (data.Domains [domain]) && !data.Domains [domain].length);

                            let rowspan = !no_results
                                ? Object.keys (data.Domains [domain]).length + 1
                                : 2 ;

                            $ (heading).append (
                                $ ("<td>").attr ("rowspan", rowspan).html (
                                    `<a target='_BLANK' href='//${domain}'>${domain}</a>`
                                )
                            );

                            $ (heading).append ($ ("<th>").text ("External domain"));
                            $ (heading).append ($ ("<th>").text ("Status"));
                            $ (heading).append ($ ("<th>").text ("DR"));

                            $ (table).append (heading);

                            if (no_results) {
                                $ (table).append (
                                    $ ("<tr><td colspan='3'>No available domains</td></tr>")
                                );
                            } else {
                                for (let external_domain in data.Domains [domain]) {
                                    let domainRow = $ ("<tr>"), d = data.Domains [domain][external_domain];

                                    let _2lvl = (d ['domain_to'] != d ['domain_to_orig'])
                                        ? ` (RegDomain = ${d ['domain_to']})`
                                        : ``;

                                    $ (domainRow).append ($ ("<td>").html (`<a target='_BLANK' href='//${d ["domain_to_orig"]}'>${d ["domain_to_orig"]} ${_2lvl}</a>`));
                                    $ (domainRow).append ($ ("<td>").html (`${d ["status"]}`));
                                    $ (domainRow).append ($ ("<td>").html (`${d ["domain_to_rating"]}`));

                                    $ (table).append (domainRow);
                                }
                            }
                        }

                        $ ("#AjaxContent").append (table);
                    }

                    $ ("#Loading").css ("visibility", "hidden");
                });

            };

            $ (document).ready (function () {
                $ ('textarea').autogrow ({
                    onInitialize: true
                });

                $ ("#GetDomainsInfo input[type='button']").click (function (e) {
                    console.log ("here");

                    getDomainsInfo (
                        $ ("#Domains").val (),
                        $ ("#ExcludeActive").is (':checked')
                    );
                    return false;
                });
            });

        </script>
    </head>
    <body>
        <div class="container">
            <h1>Domain Info</h1>
            <hr />
            <div id="GetDomainsInfo">
                <input type="hidden" name="action" value="GetStatus" />
                <div class="form-group">
                    <input id="ExcludeActive" name="ExcludeActive" type="checkbox" checked />
                    <label for="ExcludeActive">Exclude active</label>
                </div>
                <div class="form-group">
                    <textarea id="Domains" name="Domains" class="form-control" type="text"></textarea>
                </div>
                <input type="button" class="btn btn-primary" value="Submit" />
                <div id="Loading" style="visibility: hidden; " class="spinner-border spinner-border-sm ml-3"></div>
            </div>
            <hr />
            <div id="AjaxContent"></div>
        </div>
    </body>
</html>
